config/routes.rb
Zirpirani::Application.routes.draw do

    resources :users, only: [:show] do
        member do
            get "favorites"
        end
    end
  resources :authentications

  resources :meems
  resources :posts

      get 'smiley_face', controller: :posts


  resources :meems, as: :mime

  get "home/index"
  get "home/post_page"
  get "home/meme_info"
  get "home/davari"

  get 'remove_admin', controller: :users
  get 'add_admin', controller: :users
  get 'block', controller: :users
  get 'unblock', controller: :users
  get 'list', controller: :users

  devise_for :accounts, controllers: { omniauth_callbacks: "authentications", registrations: "registrations"}

  resources :social_feeds
  match '/feed' => 'social_feeds#feed',
        :as => :feed,
        :defaults => { :format => 'atom' }









  root :to => 'home#index'


end

app/models/user.rb
class User < ActiveRecord::Base
  rolify before_add: :before_change, before_remove: :before_change

  attr_accessible :account_id, :name

  belongs_to :account
  has_many :posts

  make_flagger

  validates_presence_of :name, :on => :create, :message => "can't be blank"
  validates_uniqueness_of :name, :on => :create, :message => "already taken"

  def favorite_posts
    self.flaggings.with_flag(:favorite)
  end

  def before_change(role)
    current_user ||= ""
    return false unless !current_user.empty? && current_user.has_role?(:admin)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper, UsersHelper

    before_filter :current_user_is_super_admin?, only: [:list, :remove_admin, :add_admin]

  def show
  	@user = User.find(params[:id])
  	@posts = @user.posts.page(params[:page]).per(10)
  end

  def favorites
    @user = User.find(params[:id])
    @favorite_posts = @user.favorite_posts.page(params[:page]).per(10)
  end

  def list
  	@users = User.all

    redirect_to root_path unless current_user_is_super_admin?
  end

  def remove_admin
	@user = User.find(params[:id])
            if current_user.has_role?(:super_admin) && !@user.nil?
              @user.remove_role :admin
              redirect_to list_path, success: "administration removed from #{@user.name}"
            else
              redirect_to list_path, alert: "administration error: #{@user.name}"
            end
  end

  def add_admin
	@user = User.find(params[:id])
            if current_user.has_role?(:super_admin) && !@user.nil?
              @user.add_role :admin
              redirect_to list_path, success: "administration added to #{@user.name}"
            else
              redirect_to list_path, alert: "administration error: #{@user.name}"
            end
  end

  def block
    @user = User.find(params[:id])
            if current_user.has_role?(:super_admin) && !@user.nil?
              @user.add_role :blocked
              redirect_to list_path, success: "#{@user.name} blocked"
            else
              redirect_to list_path, alert: "error blocking #{@user.name}"
            end
  end

  def unblock
    @user = User.find(params[:id])
            if current_user.has_role?(:super_admin) && !@user.nil?
              @user.remove_role :blocked
              redirect_to list_path, success: "#{@user.name} unblock"
            else
              redirect_to list_path, alert: "error unblocking #{@user.name}"
            end
  end

  private

    def current_user_is_super_admin?
        !current_user.nil? && current_user.has_role?(:super_admin)
    end


end

app/helpers/users_helper.rb
module UsersHelper

  def make_admin(user)
    current_user ||= ""
    if !current_user.empty? && current_user.has_role?(:super_admin)
      user.add_role :admin
      user.save
    else
      return false
    end
  end

  def kick_admin(user)
    current_user ||= ""
    if !current_user.empty? && current_user.has_role?(:super_admin)
      user.remove_role :admin
      user.save
    else
      return false
    end
  end

end

app/views/users/favorites.html.erb
<div class="row MarginTop">
    <div class="large-8 push-4 columns rtl">
        <div class="section-container tabs" data-section="tabs">

            <div class="button-bar">
              <ul class="button-group">
                <li><%= link_to user_path(current_user), class: "button secondary" do %>
                            اونايي كه پست <%=
                                if current_user?(@user)
                                    "کردم"
                                else
                                    "کردی"
                                end

                             %>(<%= current_user.posts.count %>)
                         <% end -%>
                 </li>
                <li>
                    <a href="#" class="button secondary active">باحالا(<%= @user.favorite_posts.size %>)</a>
                </li>
              </ul>
            </div>
            <% if current_user?(@user) %>

                <div class="panel">
                    <div class="content" data-section-content>
                        <% @favorite_posts.each do |flagging| %>
                            <%= render "posts/post", post: flagging.flaggable %>
                        <% end -%>
                    </div>
                            <%= render "shared/paginate", this: @favorite_posts %>
                </div>

            <% end -%>

        </div>
    </div>
    <%= render "shared/toolbox" %>
</div>

app/views/users/list.html.erb
<div class="row">
    <div class="large-12 columns" style="direction:ltr;">
        <table style="text-align:left;">
            <thead>
                <tr>
                    <td>Name</td>
                    <td>Email</td>
                    <td>Roles</td>
                    <td>Created at</td>
                    <td>Last signed in IP</td>
                    <td>Actions</td>
                <tr>
            </thead>
            <tbody>
                <% @users.each do |user| %>
                    <tr>
                        <td><%= user.name %></td>
                        <td><%= user.account.email %></td>
                        <td>
                            <% user.roles.each do |role| %>
                                | <%= role.name %>
                            <% end -%>
                        </td>
                        <td><%= user.account.created_at %></td>
                        <td><%= user.account.last_sign_in_ip %></td>
                        <td>
                        <% if user.has_role? :admin %>
                            <%= link_to "Remove admin", remove_admin_path(id: user.id), class: "button tiny alert" %>
                        <% else %>
                            <%= link_to "Add admin", add_admin_path(id: user.id), class: "button tiny" %>
                        <% end -%>

                        <% if user.has_role? :blocked %>
                            <%= link_to "Unblock", unblock_path(id: user.id), class: "button tiny" %>
                        <% else %>
                            <%= link_to "Block", block_path(id: user.id), class: "button tiny alert" %>
                        <% end -%>
                        </td>
                    <tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/users/show.html.erb
<div class="row MarginTop">
    <div class="large-8 push-4 columns rtl">
        <div class="section-container tabs" data-section="tabs">

            <div class="button-bar">
              <ul class="button-group">
                <li><a href="#" class="button secondary active">اونايي كه پست <%=
                            if current_user?(@user)
                                "کردم"
                            else
                                "کردی"
                            end

                         %>(<%= current_user.posts.count %>)</a></li>
                <% if current_user?(@user) %>
                    <li><%= link_to "باحالا(#{@user.favorite_posts.count})", favorites_user_path, class: "button secondary" %></li>
                <% end %>
              </ul>
            </div>

            <div class="panel">
                <div class="content" data-section-content>
                    <% @posts.each do |post| %>
                        <%= render "posts/post", post: post %>
                    <% end -%>
                </div>

                <%= render "shared/paginate", this: @posts %>
            </div>

        </div>
    </div>
    <%= render "shared/toolbox" %>
</div>