config/routes.rb
Zirpirani::Application.routes.draw do

    resources :users, only: [:show] do
        member do
            get "favorites"
        end
    end
  resources :authentications

  resources :meems
  resources :posts

      get 'smiley_face', controller: :posts


  resources :meems, as: :mime

  get "home/index"
  get "home/post_page"
  get "home/meme_info"
  get "home/davari"

  get 'remove_admin', controller: :users
  get 'add_admin', controller: :users
  get 'block', controller: :users
  get 'unblock', controller: :users
  get 'list', controller: :users

  devise_for :accounts, controllers: { omniauth_callbacks: "authentications", registrations: "registrations"}

  resources :social_feeds
  match '/feed' => 'social_feeds#feed',
        :as => :feed,
        :defaults => { :format => 'atom' }









  root :to => 'home#index'


end

app/views/shared/_ad_box.html.erb
<% custom_image ||= nil %>
    <div class="large-4 pull-8 columns">
        <div class="panel">
            <% if custom_image.nil? %>
                <%= link_to home_meme_info_path do %>
                    <%= image_tag "poolvadeh.jpeg" %>
                    <h3>ویا تو میمولوژی</h3>
                <% end -%>
            <% else %>
                <%= image_tag custom_image %>
            <% end -%>
        </div>
    </div>

app/views/shared/_comment_section.html.erb
        <div class="row">
            <div class="large-12 columns">
                <div class="commentSection">
					<!-- comments go here -->
                    <div id="fb-root"></div>
                    <script>(function(d, s, id) {
                      var js, fjs = d.getElementsByTagName(s)[0];
                      if (d.getElementById(id)) return;
                      js = d.createElement(s); js.id = id;
                      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=632971256717717";
                      fjs.parentNode.insertBefore(js, fjs);
                    }(document, 'script', 'facebook-jssdk'));
                    </script>
                  <div class="fb-comments large-12 columns" data-width="" data-num-posts="10" data-colorscheme="light"></div>
                </div>
            </div>
        </div>

app/views/shared/_meme.html.erb
            <div class="meme">
                 <div class="large-4 columns">
                    <%= image_tag(meme.image.url(:medium), als: meme.title) %>
                </div>
                <div class="large-8 columns">
                    <h2><%= meme.title %></h2>
                    <p><%= meme.description %></p>
                </div>
            </div>
        <% if account_signed_in? %>
            <% if current_user && current_user.has_role?(:admin) %>
                <%= link_to "Edit", edit_meem_path(meme) %>
            <% end -%>
       <% end -%>

<hr>

app/views/shared/_navigation.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1>
        <%# link_to "زیرپیرنی", root_path %>
        <%= link_to root_path do %>
            <div class="topLogo"></div>
        <% end -%>
    </h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Left Nav Section -->
    <ul class="left">
      <li class="show-for-small">
        <%= link_to "صفحه اصلی", root_path %>
      </li>
      <li class="divider"></li>
      <li>
        <%= link_to "میمولوژی", home_meme_info_path %>
      </li>
      <li class="divider"></li>
    </ul>
    <% if account_signed_in? %>
        <ul class="left show-for-small">
            <li class="show-for-small"><label>کاربر تووووولز</label></li>
          <li>
            <%= link_to "صفحه شخصي", user_path(current_user)  %>
          </li>
          <% if current_user && current_user.has_role?(:admin) %>
                <li><%= link_to "میم جدید", new_meem_path %></li>
                <li><%= link_to "صندلی داوری", home_davari_path %></li>
          <% end -%>
          <li><%= link_to "پست جدید", new_post_path  %></li>
          <li><%= link_to "تغییر کلمه رمز", edit_account_registration_path(current_user) %></li>
          <li><%= link_to "خروج از سایت", destroy_account_session_path, method: :DELETE %></li>
        </ul>
    <% else %>
            <ul class="left">
                <li><%= link_to "ورود به سايت", new_account_session_path %></li>
            </ul>

    <% end -%>

  </section>
</nav>

app/views/shared/_paginate.html.erb
        <%= paginate this, :window => 1, :outer_window => 3 %>

app/views/shared/_rules_box.html.erb
<div class="large-4 pull-8 columns">
    <div class="panel" style="color:#999">
            <span>زيرپيرنى فقط براى خنده است.</span>
            <hr>
            <span>پست شما نبايد چشم يا دل كسى را بيازارد.</span>
            <hr>
            <span>اگر پستت خنده دار باشه در صفخه ى اصلى جاى مى گيرد، اگر بى مزه باشه تروول با زيرپيرنى مياد تو خوابت.</span>
            <hr>
            <span>چيزى رو ده بار پست نكنيد.</span>
            <hr>
            <span>زيرپيرنى فقط براى خنده است.</span>
        </ul>
    </div>
</div>

app/views/shared/_sidebar.html.erb
    <%# render "shared/ad_box" %>
    <%# render "shared/sidebar_social" %>
    <%= render "shared/toolbox" %>
    <%= render "shared/ad_box" %>
    <%= render "shared/rules_box" %>

app/views/shared/_sidebar_social.html.erb
<div class="large-4 pull-8 columns">
    <div class="panel">
        <h1>Home#index</h1>
        <p>Find me in app/views/home/index.html.erb</p>
        <h1>Home#index</h1>
        <p>Find me in app/views/home/index.html.erb</p>
    </div>
</div>

app/views/shared/_toolbox.html.erb
<div class="large-4 pull-8 columns">
    <div class="panel">
        <%= link_to "برگرد صفحه اصلی", root_path %>
        <hr>
        <% if account_signed_in? %>
            <%= link_to "صفحه شخصي #{current_user.name}", user_path(current_user), id: "ProfileLink" %>
            <hr>
            <% if current_user && current_user.has_role?(:admin) %>
                <%= link_to "میم جدید", new_meem_path %>
                <hr>
                <%= link_to "صندلی داوری", home_davari_path %>
                <hr>
            <% end -%>
            <%= link_to "پست جدید", new_post_path, id: "newPostLink" %>
            <hr>
            <%= link_to "تغییر کلمه رمز", edit_account_registration_path(current_user) %>
            <hr>
            <%= link_to "خروج از سایت", destroy_account_session_path, method: :DELETE, id: "exitLink" %>
        <% else %>
                <%= link_to "ورود به سايت", new_account_session_path %>
        <% end -%>

    </div>
</div>

app/views/shared/_toolbox_backup.html.erb
<div class="large-4 pull-8 columns">
    <div class="panel">
        <% if account_signed_in? %>
            <%= link_to "برگرد صفحه اصلی", root_path, class: "show-for-small" %>
            <hr class="show-for-small">
            <%= link_to "صفحه شخصي", user_path(current_user), id: "ProfileLink" %>
            <hr>
            <% if account_signed_in? %>
                <% if current_user && current_user.has_role?(:admin) %>
                    <%= link_to "میم جدید", new_meem_path %>
                    <hr>
                    <%= link_to "صندلی داوری", root_path %>
                    <hr>
                <% end -%>
            <% end -%>
            <%= link_to "پست جدید", new_post_path, id: "newPostLink" %>
            <hr>
            <%= link_to "تغییر کلمه رمز", edit_account_registration_path(current_user) %>
            <hr>
            <%= link_to "خروج از سایت", destroy_account_session_path, method: :DELETE, id: "exitLink" %>
        <% else %>
                <%= link_to "ورود به سايت", new_account_session_path %>
                <hr>
                <%= link_to "ثبت نام در سایت", new_account_registration_path %>
                <hr>
        <% end -%>

    </div>
</div>

app/views/shared/google-ana.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41449943-1', 'zirpirani.com');
  ga('send', 'pageview');

</script>