config/routes.rb
Zirpirani::Application.routes.draw do

    resources :users, only: [:show] do
        member do
            get "favorites"
        end
    end
  resources :authentications

  resources :meems
  resources :posts

      get 'smiley_face', controller: :posts


  resources :meems, as: :mime

  get "home/index"
  get "home/post_page"
  get "home/meme_info"
  get "home/davari"

  get 'remove_admin', controller: :users
  get 'add_admin', controller: :users
  get 'block', controller: :users
  get 'unblock', controller: :users
  get 'list', controller: :users

  devise_for :accounts, controllers: { omniauth_callbacks: "authentications", registrations: "registrations"}

  resources :social_feeds
  match '/feed' => 'social_feeds#feed',
        :as => :feed,
        :defaults => { :format => 'atom' }









  root :to => 'home#index'


end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :user_id, :image, :source, :approved

  belongs_to :owner, class_name: "User", foreign_key: "user_id"
  make_flaggable :favorite

  validates_presence_of :title, :on => :create, :message => "can't be blank"
  validates_attachment :image,
		:presence => true,
		:content_type => { :content_type =>  ['image/png', 'image/jpg', 'image/jpeg'] },
		:size => { :in => 0..10000.kilobytes }

  has_attached_file :image, :styles => {:large => "650>"}


  def favorite_count
      if self.flaggings.with_flag(:favorite).empty?
          0
      else
          self.flaggings.with_flag(:favorite).count
      end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include SessionsHelper
  before_filter :authenticate_account!, except: :show

  def index
    redirect_to root_path
  end

  def show
    @post = Post.find(params[:id])

    if (@post.approved == 1)  || (!current_user.nil? && @post.owner == current_user)
      render :show
    else
      before_change
    end

  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post])
    @post.user_id = current_user.id
    @post.approved = 1 if current_user_is_admin?

    if @post.save
      redirect_to @post, notice: "post created."
    else
      render new, alert: "There was a problem with creating the post."
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attribtes(params[:post])
      redirect_to @post, notice: "post created."
    else
      render edit, alert: "There was a problem with saving the post."
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
        redirect_to root_path, :notice => 'Post Deleted'
    end
  end

  def smiley_face
    @post = Post.find(params[:id])
    current_user.toggle_flag(@post, :favorite)

    if current_user.has_role?(:admin)
        @post.approved = 1
        @post.save
    end

    respond_to do |format|
        format.js { render 'posts/smiley_face.js.erb', :locals => { post: @post } }
    end
  end

end

app/helpers/post_helper.rb
module PostHelper
end

app/views/posts/_header.html.erb
<% reload ||= false %>
<%="<div class=\"postHeader\">".html_safe unless reload == true %>
    <div class="large-10 columns"><h3><%= post.title %></h3></div>
    <div class="large-2 columns">
        <div class="likeContainer">
            <% if account_signed_in? %>
                <%= link_to content_tag("div", "", class: smiley_face_css_for(post)), smiley_face_path(id: post.id), remote: true %>
            <% else %>
                <%= link_to content_tag("div", "", class: "like"), new_account_session_path %>
            <% end %>
                <!-- <a href="#"><div class="like"></div></a> -->

        </div>
    </div>
<%= "</div>".html_safe unless reload == true %>

app/views/posts/_post.html.erb
<div class="row"  id="post<%= post.id.to_s %>">
    <div class="large-12 columns">
        <%= render "posts/header", post: post %>
    </div>
    <div class="large-12 columns postImg">
        <%= link_to image_tag(post.image.url(:large), als: post.title), post_path(post) %>
    </div>
    <div class="large-12 columns info">

        <% if (post.approved == 1) || (current_user_is_admin?) %>
            <a href="http://www.facebook.com/sharer/sharer.php?s=100&p[url]=<%= "http://zirpirani.com" + post_path(post) %>&p[images][0]=<%= "http://zirpirani.com" + post.image.url(:large) %>&p[title]=<%= ERB::Util.url_encode post.title %>" target="_blank" ><div class="large-6 small-6 fb_button left">بده بغلی</div></a>
            <a href="http://twitter.com/share?text=<%= ERB::Util.url_encode post.title %>&url=<%= "http://zirpirani.com" + post_path(post) %>" target="_blank"><div class="large-6 small-6 tw_button">بده بغلی</div></a>
        <% end %>

        <div class="large-12 columns postFooter">

            <span class="smileCount">آمار خنده: <%= post.favorite_count %></span>

            <span class="left dateInfo"><%= time_ago_in_words(post.created_at) %> by <%= link_to(post.owner.name, post.owner) %>
                <% if account_signed_in? %>
                     <% if current_user && current_user.has_role?(:admin) %>
                        <%= link_to "Delete", post_path(post),:confirm => 'Are you sure?', method: :delete, class: "DeletePost"  %>
                    <% end -%>
                <% end %>
            </span>
        </div>
    </div>
</div>
<hr>

app/views/posts/create.html.erb
<h1>Post#create</h1>
<p>Find me in app/views/post/create.html.erb</p>

app/views/posts/index.html.erb
<h1>Post#index</h1>
<p>Find me in app/views/post/index.html.erb</p>

app/views/posts/new.html.erb
 <script type="text/javascript">

MultipartEntity multipartEntity = new MultipartEntity(HttpMultipartMode.BROWSER_COMPATIBLE);
    for (NameValuePair nameValuePair : nameValuePairs) {
        if (nameValuePair.getName().equalsIgnoreCase("image")) {
                File imgFile = new File(nameValuePair.getValue());
                FileBody fileBody = new FileBody(imgFile, "image/jpeg");
                multipartEntity.addPart("post[image]", fileBody);
        } else {
                multipartEntity.addPart("post[" + nameValuePair.getName() + "]", new StringBody(nameValuePair.getValue()));
        }                   
    }
httpPost.setEntity(multipartEntity);
HttpResponse response = httpClient.execute(httpPost, httpContext);

</script>

 <div class="row MarginTop">
    <div class="large-8 push-4 columns panel">
        <h2>پست جدید</h2>
        <%= simple_form_for(@post, :html => { :method => :post, id: "PostNew", :class => 'custom form-vertical'}) do |f| %>
                <%= f.error_notification %>
                <%= f.input :title, :required => true %>
                <%= f.file_field :image, class: "file text" %> <br> <br>
                <%= f.input :source, placeholder: "http://www.example.com" %>
                <%= f.submit 'بده بره', class: "button grey submitBtn homeBtn right" %>
        <% end %>
        <div style="margin-top: 100px;" id="loadgif"><%= image_tag "load.gif" %></div>
    </div>
    <%= render "shared/toolbox" %>
</div>

app/views/posts/show.html.erb
<div class="row MarginTop">
    <div class="large-8 push-4 columns">
        <div class="panel">
             <%= render @post %>
    <h2>کامنتها</h2>
    <hr>
            <%= render "shared/comment_section" %>
        </div>
    </div>
            <%= render "shared/sidebar" %>
</div>

app/views/posts/smiley_face.js.erb
$("div#post<%= post.id.to_s %> div.postHeader").html("<%= escape_javascript(render('posts/header', post: @post, reload: true)) %>")
$("div#post<%= post.id.to_s %> span.smileCount").html("تعداد خنده: <%= post.favorite_count %>")

app/views/posts/update.html.erb
<h1>Post#update</h1>
<p>Find me in app/views/post/update.html.erb</p>